#!/usr/bin/env python

import qrencode
import sys

from PIL import Image

SIZE = 200

if len(sys.argv) < 3:
    print "Usage: %s <file> <data>" % sys.argv[0]
    sys.exit(1)

file = sys.argv[1]
data = sys.argv[2]
(_, size, img) = qrencode.encode_scaled(data, SIZE)
img.save(file)
