#!/usr/bin/env bash

xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita"
if [[ -L "$HOME/.config/alacritty/alacritty.toml" ]]; then
    cd $HOME/.config/alacritty/
    rm alacritty.toml
    ln -s alacritty_light.toml alacritty.toml
fi
