#!/bin/sh

XCAPE=/usr/bin/xcape
if [ -f $XCAPE ]; then
    xkbcomp -I$HOME/.xkb $HOME/.xkb/keymap/personal_keymap $DISPLAY 2> /dev/null
    xmodmap -e "keycode any = Return"
    xcape -t 250 -e "ISO_Level3_Shift=Return"
else
    echo "Error: Unable to find xcape."
fi

