#!/usr/bin/env python

import sys
import subprocess
import re
import os

if len(sys.argv) < 2:
    print "Usage: %s <process name>" % sys.argv[0]
    sys.exit(1)

try:
    print "Press enter to kill the process."
    while True:
        raw_input("")
        p = subprocess.Popen(["ps", "x"], stdout=subprocess.PIPE)
        output = p.stdout.read()
        pattern = "[0-9]:[0-9][0-9] %s" % sys.argv[1]
        for line in output.split("\n"):
            if re.search(pattern, line):
                pid = re.match("^ *([0-9]+) .*", line).group(1)
                os.system("kill -9 %s" % pid)
                print "Killed process %s" % pid
except KeyboardInterrupt:
    pass
