#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 [profile]"
    echo "  Profiles: triple"
elif [ "$1" = "triple" ]; then
    xrandr --output LVDS1 --mode 1600x900
    xrandr --output VGA1 --mode 2560x1024 --right-of LVDS1
fi
