#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 [profile]"
    echo "  Profiles: triple|mobile|gaming|external"
elif [ "$1" = "triple" ]; then
    xrandr --output LVDS1 --mode 1600x900
    xrandr --output VGA1 --mode 2560x1024 --right-of LVDS1
elif [ "$1" = "mobile" ]; then
    xrandr --output LVDS1 --mode 1600x900
    xrandr --output VGA1 --off
elif [ "$1" = "gaming" ]; then
    xrandr --output LVDS1 --off
    xrandr --output VGA1 --mode 1280x1024
elif [ "$1" = "external" ]; then
    xrandr --output LVDS1 --off
    xrandr --output VGA1 --mode 1600x900
fi
